<a href="https://colab.research.google.com/github/vvinjamoori/Python/blob/main/Food_Delivery_Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
votes = np.arange(100,2000,75)

In [ ]:
votes

array([ 100,  175,  250,  325,  400,  475,  550,  625,  700,  775,  850,
        925, 1000, 1075, 1150, 1225, 1300, 1375, 1450, 1525, 1600, 1675,
       1750, 1825, 1900, 1975])

In [ ]:
#sorting

np.sort(votes)

array([ 100,  175,  250,  325,  400,  475,  550,  625,  700,  775,  850,
        925, 1000, 1075, 1150, 1225, 1300, 1375, 1450, 1525, 1600, 1675,
       1750, 1825, 1900, 1975])

In [ ]:
x=np.array([7,77,5,44,3])

In [ ]:
y= np.sort(x)

In [ ]:
y

array([ 3,  5,  7, 44, 77])

In [ ]:
np.sort(x)[::-1]

array([77, 44,  7,  5,  3])

In [ ]:
votes_descending= np.sort(votes)[::-1]

In [ ]:
votes_descending

array([1975, 1900, 1825, 1750, 1675, 1600, 1525, 1450, 1375, 1300, 1225,
       1150, 1075, 1000,  925,  850,  775,  700,  625,  550,  475,  400,
        325,  250,  175,  100])

In [ ]:
#get top 10 votes in desc
np.sort(votes)[::-1][:10]

array([1975, 1900, 1825, 1750, 1675, 1600, 1525, 1450, 1375, 1300])

In [ ]:
restaurants=['R1','R2','R3','R4','R5','R6','R7','R8','R9','R10','R11','R12']
ratings=[11,10,20,40,900,30,12,17,16,33,88,22]

In [ ]:
#find the restaurants having more than 30 ratings #previous class practice

restaurants = np.array(restaurants)
ratings = np.array(ratings)

In [ ]:
ratings>=30

array([False, False, False,  True,  True,  True, False, False, False,
        True,  True, False])

In [ ]:
restaurants[ratings>=30]

array(['R4', 'R5', 'R6', 'R10', 'R11'], dtype='<U3')

In [ ]:
z=np.array([2556,  918,  775,772,  504,  402,  324,  286,  1660,   88])

In [ ]:
np.argsort(z) # sorts and gets you the index of the actual number

array([9, 7, 6, 5, 4, 3, 2, 1, 8, 0])

In [ ]:
np.sort(z)

array([  88,  166,  286,  324,  402,  504,  775,  787,  918, 2556])

In [ ]:
array_2d = np.array([[34, 11, 8],
                     [7, 45, 18],
                     [9, 23, 20]])

In [ ]:
np.sort(array_2d)

array([[ 8, 11, 34],
       [ 7, 18, 45],
       [ 9, 20, 23]])

In [ ]:
#customization

np.sort(array_2d, axis=0) #row sorting

array([[ 7, 11,  8],
       [ 9, 23, 18],
       [34, 45, 20]])

In [ ]:
np.sort(array_2d, axis=1) #column sorting

array([[ 8, 11, 34],
       [ 7, 18, 45],
       [ 9, 20, 23]])

In [ ]:
ratings = np.array([4.9, 4.1, 4.8])
votes = np.array([ 775,  787,  918])

In [ ]:
# element wise multiplication

ratings * votes

array([3797.5, 3226.7, 4406.4])

In [ ]:
numeric_data = np.arange(11,20).reshape(3,3)

In [ ]:
numeric_data

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
transformation_matrix = np.array([[1.2, 0.8, 0.5],
                                   [0.5, 1.5, 1.0],
                                   [0.7, 0.6, 1.8]])

In [ ]:
numeric_data @ transformation_matrix #matrix multiplication

array([[28.3, 34.6, 40.9],
       [35.5, 43.3, 50.8],
       [42.7, 52. , 60.7]])

In [ ]:
numeric_data * transformation_matrix #element wise multiplication #reduce the brightness

array([[13.2,  9.6,  6.5],
       [ 7. , 22.5, 16. ],
       [11.9, 10.8, 34.2]])

In [ ]:
np.dot(numeric_data,transformation_matrix ) #matrix multiplication

array([[28.3, 34.6, 40.9],
       [35.5, 43.3, 50.8],
       [42.7, 52. , 60.7]])

In [ ]:
np.matmul(numeric_data,transformation_matrix ) #matrix multiplication

array([[28.3, 34.6, 40.9],
       [35.5, 43.3, 50.8],
       [42.7, 52. , 60.7]])

In [ ]:
############

array_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_2d * 0.8 #numpy is intelligent #broadcasting

array([[0.8, 1.6, 2.4],
       [3.2, 4. , 4.8]])

In [ ]:
array_2d + 0.8

array([[1.8, 2.8, 3.8],
       [4.8, 5.8, 6.8]])

In [ ]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array1 = np.array([1, 2, 3])

In [ ]:
array_2d + array1

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10, 20]])

In [ ]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [ ]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[10], [20], [30]])

In [ ]:
x= np.tile (array1,(3,1))

In [ ]:
y= np.tile(array2 , (1,3))

In [ ]:
x + y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
array_2d_2 = np.array([[1,2,3,4,5,6]])
array_2d_3 = np.array([[1],[2],[3],[4],[5],[6]])

In [ ]:
array_2d_2 + array_2d_3

array([[ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
def categorize_rating(rating):
    if rating < 4:
        return 'low'
    else:
        return 'high'



['high' 'high' 'high']


In [ ]:
ratings = np.array([4.9, 4.1, 4.8, 3.1,2.5,3.3])

In [ ]:
lister=[]
for i in ratings:
    lister.append(categorize_rating(i))

In [ ]:
lister

['high', 'high', 'high', 'low', 'low', 'low']

In [ ]:
def categorize_rating(rating):
    if rating < 4:
        return 'low'
    else:
        return 'high'

categorize_rating_np= np.vectorize(categorize_rating) ############

ratings = np.array([4.9, 4.1, 4.8, 3.1,2.5,3.3])

categorize_rating_np(ratings)

array(['high', 'high', 'high', 'low', 'low', 'low'], dtype='<U4')

In [ ]:
def discount_cost(rate, cost):
    "Apply a 10% discount if the rating is 4.0 or higher."""
    if rate >= 4.0:
        return cost * 0.9
    else:
        return cost

discount_cost_v= np.vectorize(discount_cost) #############

In [ ]:
discount_cost_v (array1, array2)