<a href="https://colab.research.google.com/github/vvinjamoori/Python/blob/main/Python_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world")

Hello world


In [ ]:
5+9

14

In [ ]:
100000000000 +1908887475947974957945

1908887476047974957945

In [ ]:
 x = 3
 y = 5

 z = x + y

 print(z)

8


In [ ]:
#datatype

type(x)

int

In [ ]:
type(y)

int

In [ ]:
y = 5.1

In [ ]:
type(y)

float

In [ ]:
x = 'three'

In [ ]:
type(x)

str

In [ ]:
x + y

TypeError: can only concatenate str (not "float") to str

In [ ]:
y = '5.1'

In [ ]:
x + y

'three5.1'

In [ ]:
x= 3
y = 5.1

z = x + y

In [ ]:
z

8.1

In [ ]:
friends = [2,3,4,5,6,7]

In [ ]:
type(friends)

list

In [ ]:
friends = [2,'Tina','Suraj',True,6.1,7]

In [ ]:
#list can accomodate different data types

In [ ]:
a = [1,2,'abc']
type(a)

list

In [ ]:
[1,2,3,4,5,6] *2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [ ]:
x= [11,22,33,44,55,66]
for i in x:
  print(i * 2)

22
44
66
88
110
132


In [ ]:
#numerical operations in python could be challenging

import numpy as np

In [ ]:
x = np.array([11,22,33,44,55,66])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x * 2

array([ 22,  44,  66,  88, 110, 132])

In [ ]:
x= [11,22,33,44,55,66]
for i in x:
  print(i * 2)

In [ ]:
x = np.array([11,22,33,44,55,66])
x * 2

In [ ]:
#why numpy array opeartion was faster


In [ ]:
friends = np.array([2,'Tina','Suraj',True,6.1,7] )

In [ ]:
friends

array(['2', 'Tina', 'Suraj', 'True', '6.1', '7'], dtype='<U32')

In [ ]:
friends * 2

TypeError: The 'out' kwarg is necessary. Use numpy.strings.multiply without it.

In [ ]:
x= np.array ([1,2,3,4,5.1,7,8,9])

In [ ]:
x

array([1. , 2. , 3. , 4. , 5.1, 7. , 8. , 9. ])

In [ ]:
x * 2

array([ 2. ,  4. ,  6. ,  8. , 10.2, 14. , 16. , 18. ])

In [ ]:
import time
import numpy as np

# Define a large size for our data structures
size = 10000000  # 10 million elements

# --- Python List ---

# Create a Python list
python_list = list(range(size))

# Measure time for element-wise multiplication
start_time = time.time()
python_list_result = [x * 2 for x in python_list]
end_time = time.time()
python_list_time = end_time - start_time
print(f"Time taken for Python list operation: {python_list_time:.4f} seconds")

# --- NumPy Array ---

# Create a NumPy array
numpy_array = np.arange(size)

# Measure time for element-wise multiplication
start_time = time.time()
numpy_array_result = numpy_array * 2
end_time = time.time()
numpy_array_time = end_time - start_time
print(f"Time taken for NumPy array operation: {numpy_array_time:.4f} seconds")

print(f"\nNumPy array was {python_list_time / numpy_array_time:.2f} times faster than Python list.")

Time taken for Python list operation: 1.1672 seconds
Time taken for NumPy array operation: 0.0548 seconds

NumPy array was 21.30 times faster than Python list.


### Why NumPy arrays are faster:

1.  **Memory Layout**: NumPy arrays are stored in a contiguous block of memory, which allows for highly efficient CPU cache utilization and vectorization (applying operations to entire arrays at once).
2.  **Fixed Type**: All elements in a NumPy array must be of the same data type. This homogeneity simplifies data storage and processing, as Python doesn't have to check the type of each element during an operation.
3.  **Optimized C Implementation**: The core operations in NumPy are implemented in C, which provides significant performance advantages over Python's interpreted code. This means that numerical computations are performed at a lower level, much closer to the hardware.
4.  **Vectorization**: NumPy encourages 'vectorized' operations, where operations are applied to the entire array rather than iterating through elements one by one (as is common with Python lists). This eliminates the overhead of Python loops, which can be very slow.

In [ ]:
import numpy as np

# Create a 1D NumPy array for votes with integer values
votes = np.array([120, 50, 300, 80, 250, 150, 400, 90, 180, 320])

# Create a 1D NumPy array for cost_for_two with integer values
cost_for_two = np.array([500, 200, 1000, 300, 700, 450, 1200, 250, 600, 900])

print("Votes array:", votes)
print("Cost for two array:", cost_for_two)

Votes array: [120  50 300  80 250 150 400  90 180 320]
Cost for two array: [ 500  200 1000  300  700  450 1200  250  600  900]


In [ ]:
#Data Exploration

votes.shape

(10,)

In [ ]:
cost_for_two.shape

(10,)

In [ ]:
np.set_printoptions(suppress=True, precision=4)

In [ ]:
import numpy as np

# Create a 2D NumPy array combining votes and cost_for_two
# Each row can represent an item, with the first column as votes and second as cost_for_two
votes_cost_for_two = np.array([
    [120, 500],
    [ 50, 200],
    [300, 1000],
    [ 80, 300],
    [250, 700],
    [150, 450],
    [400, 1200],
    [ 90, 250],
    [180, 600],
    [320, 900]
])

# Create a 2D NumPy array combining ratings and no_of_reviews
# This will include both integer and float values
ratings_no_of_reviews = np.array([
    [4.5, 1500],
    [3.8,  720],
    [4.9, 2100],
    [3.2,  300],
    [4.1, 1100],
    [2.9,  180],
    [4.7, 3000],
    [3.5,  500],
    [4.2,  950],
    [3.9, 1300]
])

print("Votes and Cost for Two Array:\n", votes_cost_for_two)
print("\nRatings and Number of Reviews Array:\n", ratings_no_of_reviews)

Votes and Cost for Two Array:
 [[ 120  500]
 [  50  200]
 [ 300 1000]
 [  80  300]
 [ 250  700]
 [ 150  450]
 [ 400 1200]
 [  90  250]
 [ 180  600]
 [ 320  900]]

Ratings and Number of Reviews Array:
 [[   4.5 1500. ]
 [   3.8  720. ]
 [   4.9 2100. ]
 [   3.2  300. ]
 [   4.1 1100. ]
 [   2.9  180. ]
 [   4.7 3000. ]
 [   3.5  500. ]
 [   4.2  950. ]
 [   3.9 1300. ]]


In [ ]:
votes_cost_for_two.shape #10 rows and 2 columns

(10, 2)

In [ ]:
votes.ndim

1

In [ ]:
votes_cost_for_two.ndim

2

In [ ]:
votes.size

10

In [ ]:
votes_cost_for_two.size

20

In [ ]:
a = np.array(['1.2', '2.5', '3.6', '4.8'])

In [ ]:
a.dtype #type of data element inside array

dtype('<U3')

In [ ]:
#how do I fix an array that has elements stored as strings
# Change the datatype
#convert
#Typecast ---> Technical term

In [ ]:
a= a.astype(float)

In [ ]:
a.dtype

dtype('float64')

In [ ]:
#indexing--> Next class